
name: coupons # yml文件名https://blog.csdn.net/qq_44732432/article/details/124713585
 
on:
  push:
    branches:
      - main
  schedule:   
    - cron: '0 9 * * *'   # 定时运行的时间，国际标准时间，北京时间要+8
 
jobs:
  run-coupons: # 任务名
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main  #采用main分支下的
           
      - name: Setup Node.js
        uses: actions/setup-node@v2  #安装node.js
        with:
          node-version: '23'
          
      - name: Install Dependency       
        run: |
          npm install
          npm install node-fetch
          node ./node.js
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
                apiToken: ${{ secrets.CF_TOKEN }}
                accountId: ${{ secrets.CF_ID }}
                projectName: nymey
                directory: cloudflare
                wranglerVersion: '3'

                
